export const enum OurExceptionType {
  LOGIN_EMAIL_CONFIRMATION_REQUIRED = 'LOGIN_EMAIL_CONFIRMATION_REQUIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  REVIEW_DOES_NOT_EXIST = 'REVIEW_DOES_NOT_EXIST',
  UNKNOW_SORTING_KEY = 'UNKNOWN_SORTING_KEY',
  ICE_CREAM_DOES_NOT_EXIST = 'ICE_CREAM_DOES_NOT_EXIST',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  INVALID_OBJECT_ID = 'INVALID_OBJECT_ID',
  IS_VEGAN_WRONG_FORMAT = 'IS_VEGAN_WRONG_FORMAT',
}
