export const enum OurExceptionType {
  LOGIN_EMAIL_CONFIRMATION_REQUIRED = 'LOGIN_EMAIL_CONFIRMATION_REQUIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  LINK_NAME_ALREADY_EXISTS = 'LINK_NAME_ALREADY_EXISTS'
}
