export const enum OurExceptionType {
  LOGIN_EMAIL_CONFIRMATION_REQUIRED = 'LOGIN_EMAIL_CONFIRMATION_REQUIRED',
  INVALID_TOKEN = 'INVALID_TOKEN',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  REVIEW_ALREADY_EXISTS = 'REVIEW_ALREADY_EXISTS',
  UNKNOW_SORTING_KEY = 'UNKNOWN_SORTING_KEY',
  ICE_CREAM_DOES_NOT_EXIST = 'ICE_CREAM_DOES_NOT_EXIST',
  USER_DOES_NOT_EXIST = 'USER_DOES_NOT_EXIST'
}
