name: Deploy (prod)

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build and push
        uses: './.github/templates/build-and-push'
        with:
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-token: ${{ secrets.DOCKERHUB_TOKEN }}
          image-name: mcdominik/ice-bunch-backend-prod
      - name: Clean
        uses: './.github/templates/clean'
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          image-name: mcdominik/ice-bunch-backend-prod
      - name: Deploy
        uses: './.github/templates/deploy'
        with:
          # const
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          port: ${{ secrets.PORT }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          application-port: 3002
          email-port: ${{ secrets.EMAIL_PORT }}
          email-host: ${{ secrets.EMAIL_HOST }}
          email-password: ${{ secrets.EMAIL_PASSWORD }}
          email-user: ${{ secrets.EMAIL_USER }}
          mongo-password: ${{ secrets.MONGO_PASSWORD }}
          jwt-secret: ${{ secrets.JWT_SECRET }}
          # env
          our-env: prod
          image-name: mcdominik/ice-bunch-backend-prod
          container-port: 5137
          frontend-url: ${{ secrets.FRONTEND_URL }}
          backend-url: ${{ secrets.BACKEND_URL }}
          mongo-host: ${{ secrets.MONGO_HOST }}
          cloudinary-api-key: ${{ secrets.CLOUDINARY_API_KEY }}
          cloudinary-api-secret: ${{ secrets.CLOUDINARY_API_SECRET }}
          cloudinary-name: ${{ secrets.CLOUDINARY_NAME }}
