name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: mcdominik/icebunch-backend:latest
  update-VPS-container:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Update image inside VPS
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.MIKRUS_PORT }}
          KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker stop $(docker ps -q --filter ancestor=mcdominik/icebunch-backend )
            docker system prune -f
            docker pull mcdominik/icebunch-backend
            docker run -d -e CLOUDINARY_API_KEY=${{secrets.CLOUDINARY_API_KEY}} -e CLOUDINARY_API_SECRET=${{secrets.CLOUDINARY_API_SECRET}} -e CLOUDINARY_NAME=${{secrets.CLOUDINARY_NAME}} -e JWT_SECRET=${{secrets.JWT_SECRET}} -e FRONTEND_URL=${{secrets.FRONTEND_URL}} -e MONGO_PASSWORD=${{secrets.MONGO_PASSWORD}} -e MONGO_HOST=${{secrets.MONGO_HOST}} -e EMAIL_HOST=${{secrets.EMAIL_HOST}} -e EMAIL_PORT=${{secrets.EMAIL_PORT}} -e EMAIL_USER=${{secrets.EMAIL_USER}} -e EMAIL_PASSWORD=${{secrets.EMAIL_PASSWORD}}  -p 4137:3002 mcdominik/icebunch-backend